<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="InthePark.aspx.cs" Inherits="shakespeareinthepark.org.Content.Tickets.InthePark" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div class="tickets font_15px">
    <div class="blackbox">FREE TICKETS IN THE PARK</div>
    <div class="content">
        <p><b>​Free tickets are distributed on each performance day via the Free Lines at the Delacorte Theater in Central Park.</b> We recognize that free ticket lines can sometimes be long and we appreciate the time and dedication of everyone.  These ticket policies are designed to maximize fairness for visitors and to make everyone’s experience as smooth and pleasant as possible.​</p>
        <p class="bold">All performances of <i>The Comedy of Errors</i> and <i>Love's Labour's Lost, A New Musical</i> will begin at 8:30 p.m.​​</p>
        <p>Free tickets are also distributed on this website each performance day by random drawing via our Virtual Ticketing system. <a href="/content/Tickets/VirtualTicketing.aspx" class="lowercase">Request tickets here</a>.</p>
        <p>The theater will open approximately 30-minutes prior to curtain. Latecomers will be seated at the discretion of theater management. ​The running time of each show is approximately 90-minutes with no-intermission.​</p>
        <p class="bold red">﻿ FREE TICKET DISTRIBUTION AND LINE POLICIES</p>
        <p><b>Free tickets are distributed at 12pm (NOON) every day there is a public performance.​</b><br />Performance days will vary from week to week.  Check the performance calendar for more information.​</p>
        <p><b>Each person (age 5+) may receive up to two (2) tickets, while supplies last.​</b><br />Seat locations are distributed randomly; not based on a person’s position in the line.</p>
        <p class="bold">There are separate lines for accessible tickets for senior citizens (65+) and patrons with disabilities.​</p>
        <p><b>To allow as many different people as possible to attend performances throughout the summer, each person will be limited to receiving free tickets to TWO (2) PERFORMANCES of each production.</b><br />This limit applies not just to the particular performance for which you are currently in line, but for the entire run of that performance at the Delacorte Theater.</p>
        <p>People waiting for free tickets must line up along the path designated by The Public Theater staff and The Parks Department.</p>
        <p>Ticket holders may bring food and drink inside the theater.  No glass containers allowed.</p>
        <p>Ticket holders with children under 5 may obtain a lap-seating voucher for their child when entering the theater through their assigned gate.  Strollers of any kind are not allowed in the theater.</p>
        <p>​​​​​​​​​​The Public Theater reserves the right to deny or revoke tickets and to refuse admission admission to anyone for any reason including, but not limited to, establishing a separate line inside the park before 6am, line cutting, jumping ahead, saving spots, adding additional people, using a replacement person, leaving the line for an extended period of time (except to use the restroom or visit the Public Fare food stand), smoking, drunken, disorderly or suspicious conduct, harassment of any kind towards The Public Theater staff and/or other persons, or exceeding the two (2) performances per production ticket limit.</p>
        <p>After the final ticket is distributed for that day’s performance, anyone who did not obtain a ticket may begin to form a stand-by line. The Public Theater staff will begin to monitor this line, starting at 6:30pm. Pending availability, free stand-by tickets will be distributed, 1 per person. </p>
        <p>The Public Theater reserves the right to deny tickets, including tickets to future performances this season and in future seasons, to anyone participating on a secondary market in the selling or obtaining of tickets that The Public Theater offers for free, and to revoke such tickets or to deny admission to anyone found in possession of such obtained tickets.  Any known activity regarding the misuse of free tickets should be reported to The Public Theater staff. The Public Theater does not condone ticket scalping. It undermines the spirit of Free Shakespeare in the Park and is unfair to those who wait in line.</p>
        <p><b>Only tickets obtained from the Delacorte Theater Box Office or The Public Theater will be accepted as forms of entry into the theater.</b> Tickets obtained from unauthorized sources may have been lost or stolen, obtained improperly, or may be counterfeit. The Public Theater reserves the right to deny admission to the holder of any such ticket. Any such tickets obtained are at your own risk.</p>
        <p>By accepting or using a ticket from the Delacorte Theater or The Public Theater, you agree to comply with the Free Ticket Distribution and Line Policies and, if applicable, any additional terms and conditions set forth on the back of the ticket, and acknowledge that such policies are reasonable to preserve the enjoyment of the event for all.</p>
        <p>Any disagreement relating to ticket distribution or line policy will be settled by The Public Theater in its sole discretion. The Public Theater reserves the right to create additional rules as needed.</p>
        <p><b>The ticket distribution lines and area surrounding the Delacorte Theater are monitored by video surveillance. </b> By waiting in line, you consent to being recorded and to comply with The Public Theater's Free Ticket Distribution and Line Policy.</p>
        <p><b>WAITING FOR TICKETS IS AT YOUR OWN RISK.</b> The Public Theater assumes no responsibility for the safety of persons waiting for tickets or for their property. The Public Theater staff and employees are responsible solely for the enforcement of the Free Ticket Distribution and Line Policies. In case of emergency, please notify a police officer or call 911.</p>
   </div>
</div>
</asp:Content>
