<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="faq.aspx.cs" Inherits="shakespeareinthepark.org.Content.About.faq" %>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div id="faq" class="font_15px"><br />
    <p class="font_21px bold red">FREQUENTLY ASKED QUESTIONS</p>
    <p><b>What is Free Shakespeare in the Park?</b><br />Free Shakespeare in the Park is The Public Theater's annual season of free plays at the Delacorte Theater in New York City's Central Park.</p>
    <p><b>What plays are being performed at Free Shakespeare in the Park this year?</b><br />This year, Free Shakespeare in the Park will feature <a class="italic" href="/content/shows and events/thecomedyoferrors.aspx">The Comedy of Errors</a>, by William Shakespeare and directed by Daniel Sullivan, and <a class="italic" href="/content/shows and events/loveslabourslost.aspx">Love's Labour's Lost, A New Musical</a>, an adaptation of Shakespeare's comedy by Michael Friedman and Alex Timbers.</p>
    <p><b>What is the schedule of the two Free Shakespeare in the Park productions this summer?</b><br />The Comedy of Errors runs May 28 - June 30, and Love's Labour's Lost, A New Musical runs July 23 - August 18. For a full schedule, <a href="/Content/Plan Your Visit/calendar.aspx">click here</a>.</p>
    <p><b>What time do performances begin?</b>All performances of The Comedy of Errors and Love's Labour's Lost, A New Musical begin at 8:30pm. For start times for special events, please visit each event's individual page. </p>
    <p><b>How do I get tickets?</b><br />There are a number of ways to get free tickets to Shakespeare in the Park, including the <a href="/Content/Tickets/inthepark.aspx">Free Ticket Lines</a> at the Delacorte Theater in Central Park and on this website via our <a href="/Content/Tickets/virtualticketing.aspx">Virtual Ticketing</a> system. For more information, see the <a href="/Content/Tickets">Tickets</a> page. </p>
    <p><b>How many tickets can I get by waiting in line?</b><br />Each person waiting in line can receive up to two tickets, subject to availability. <a href="/Content/Tickets/inthepark.aspx">Click here</a> for more information.</p>
    <p><b>Are there any separate ticket policies for senior citizens or people with disabilities?</b><br />There are separate <a href="/Content/Tickets/inthepark.aspx">Free Ticket Lines</a>at the Delacorte Theater in Central Park for senior citizens and for people with disabilities. In addition, there are separate daily drawings for senior citizens and people with disabilities online via our <a href="/Content/Tickets/virtualticketing.aspx">Virtual Ticketing</a> system. For more information, see the <a href="/Content/Tickets">Tickets</a> page.</p>
    <p><b>Can I reserve seats to Shakespeare in the Park in advance?</b> As a thank you for their generosity and help in keeping Free Shakespeare in the Park free for all, we are able to offer our Summer Supporters, Fellows, and Partners reserved seats to Shakespeare in the Park. <a href="/Content/Support">Click here</a> for more information or to donate today.</p>
    <p><b>What if it rains?</b><br />No performance will be canceled before 8:30pm, even if it’s raining. We may delay the beginning of the performance, but will perform if and when possible and safe for the actors.</p>
    <p><b>Why can't I be in the Park before 6am?</b><br />Central Park is closed between the hours of 1:00AM and 6:00AM. NYPD will patrol the Delacorte area and issue summons to anyone in the Park before its official open time. If you choose to line up before 6:00AM, please do so along the east side of Central Park West starting at 81st Street. A Public Theater line monitor will escort the line in at 6:00 AM. The Public Theater neither suggests nor condones lining up before the park opens at 6:00AM.</p>
    <p><b>Why are the lines for Shakespeare in the Park so long?</b><br />Tens of thousands of free tickets are made available to Free Shakespeare in the Park each summer. While we do our best to accommodate everyone who would like to attend a performance, the demand for tickets is always greater than the number of seats we have available. We appreciate your patience and are working very hard to ensure that the process remains as smooth and equitable as possible.</p>
    <p><b>Are there group tickets to Shakespeare in the Park?</b><br />Free tickets to Shakespeare in the Park are not available for group reservations. If you would like to attend a performance as a group, the group can wait in the line at the Delacorte Theater, or you can consider the <a href="http://www.publictheater.org/content/view/47/122/" target="_blank">Delacorte Investors</a> program.</p>
</div>
</asp:Content>


