<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="history.aspx.cs" Inherits="shakespeareinthepark.org.Content.About.history" %>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div class="about">
<div class="blackbox">HISTORY</div>
<div class="content">
<p>Founded by Joseph Papp as the Shakespeare Workshop and now one of the nation's preeminent cultural institutions, The Public Theater is an American theater in which all the country's voices, rhythms, and cultures converge. Under the leadership of Artistic Director Oskar Eustis and Executive Director Patrick Willingham, The Public is dedicated to embracing the complexities of contemporary society and nurturing both artists and audiences, as it continues Joseph Papp's legacy of creating a place of inclusion and a forum for ideas.</p>
<p>The Public Theater produces new plays, musicals, productions of Shakespeare, and other classics in its headquarters on Lafayette Street (the former Astor library, which opened as The Public Theater in 1967 with the world premiere of the musical Hair) and at the Delacorte Theater, its permanent summertime home of free Shakespeare in the Park each summer.</p>
<p>Celebrating its 51st Anniversary, the Delacorte Theater officially opened in Central Park on June 18, 1962 with <i>The Merchant of Venice</i>, directed by Joseph Papp and Gladys Vaughan and featuring George C. Scott as Shylock.<i>The Merchant of Venice</i> was followed that summer by a production of <i>The Tempest</i>, directed by Gerald Freedman and featuring Paul Stevens as Prospero and James Earl Jones as Caliban. The first Delacorte summer season concluded with <i>King Lear</i>, directed by Joseph Papp and Gladys Vaughan and featuring Frank Silvera as Lear.  Since then more than 100 productions have been presented for free at the Delcorte Theater. Highlights of past Delacorte productions include <i>Othello</i> in 1964 with James Earl Jones; <i>Hamlet</i> in 1975 with Sam Waterston; <i>The Taming of the Shrew</i> in 1978 with Raul Julia and Meryl Streep; <i>The Pirates of Penzance</i> in 1980 with Kevin Kline and Linda Ronstadt; <i>Henry V</i> in 1984 with Kevin Kline; <i>Much Ado About Nothing</i> in 1988 with Kevin Kline and Blythe Danner; <i>Richard III</i> in 1990 with Denzel Washington; <i>Othello</i> in 1991 with Raul Julia and Christopher Walken; <i>The Tempest</i> in 1995 with Patrick Stewart; <i>The Seagull</i> in 2001 with Natalie Portman, Meryl Streep, Kevin Kline and Philip Seymour Hoffman; <i>Mother Courage</i> in 2006 with Meryl Streep and Kevin Kline; <i>Macbeth</i> in 2006 with Liev Schreiber; <i>HAIR</i> in 2008 with Jonathan Groff and Will Swenson; <i>Twelfth Night in 2009 with Anne Hathaway</i>; <i>The Merchant of Venice</i> in 2010 with Al Pacino and Lily Rabe; and most recently last summer's acclaimed productions of <i>As You Like It</i> and <i>Into the Woods</i>.</p>
</div>
</div>
</asp:Content>


